apiVersion: v1
kind: Service
metadata:
  name: {{ include "py-app.fullname" . }}
spec:
  selector:
    app: my-app
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
