apiVersion: v1
kind: Service
metadata:
  name: release-name-py-app
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: custom-port
      protocol: TCP
      port: 5001
      targetPort: 5001
  selector:
    app: release-name-py-app
